services:
  fastapi:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      EMBEDDING_BATCH_SIZE: ${EMBEDDING_BATCH_SIZE:-500}
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
