services:
  db:
    image: pgvector/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - rag-network

networks:
  rag-network:
    name: rag-network

volumes:
  pgdata2:
